name: second job
on: workflow_dispatch
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: first ste
        run: |
        echo "hi cont "
        echo "second the line"
        echo "third line"
